[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llm_plx"
version = "0.1.0"
dependencies = ["loguru", "python-dotenv"]

[project.scripts]
llm_plx = "llm_plx.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
